name: Docker Image CI

on:
  push:
    branches: [ development ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file src/SME.SERAp.Prova.Api/Dockerfile --tag registry.sme.prefeitura.sp.gov.br/development/sme-prova-serap-api 
